# Omakase Ruby styling for Rails
# Manual inheritance due to bundler constraints in this environment

plugins:
  - rubocop-performance
  - rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - "data/**/*"
    - "db/schema.rb"
    - "vendor/**/*"

# All cops except your using extensions are disabled by default.
Bundler:
  Enabled: false
Gemspec:
  Enabled: false
Layout:
  Enabled: false
Lint:
  Enabled: false
Metrics:
  Enabled: false
Naming:
  Enabled: false
Performance:
  Enabled: false
  Exclude:
    - "test/**/*"
Rails:
  Enabled: false
Security:
  Enabled: false
Style:
  Enabled: false

# Key omakase-style configurations that eliminate "squiggly lines"
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

# Enable only essential layout and style cops
Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/CommentIndentation:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/HashAlignment:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Max: 120

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/MutableConstant:
  Enabled: true

# Your own specialized rules go here